Join count filter criteria
stashapp/stash pull request #1254
Opened 2021-04-01 00:56 UTC by WithoutPants

Extension of #1234 

* Adds `tag_count` criterion and sorting option to Performer, Scene, Gallery and Image filters.
* Adds `performer_count` criterion and sorting option to Scene, Gallery and Image filters.
* Adds `scene_count`, `image_count`, `gallery_count` criteria to Performer filter.

2021-04-01 14:05 UTC, peolic requested changes
Seems to work well (have only tested scenes & performers (+ performer tags), no gallery or images)

2021-04-01 14:05 UTC, peolic commented on graphql/schema/types/filters.graphql
> +  gallery_count: IntCriterionInput
```suggestion
  """Filter by image count"""
  image_count: IntCriterionInput
  """Filter by gallery count"""
  gallery_count: IntCriterionInput
```

2021-04-01 23:08 UTC, mrbrdo requested changes
I believe that filter query needs the IFNULL addition.

2021-04-01 23:08 UTC, mrbrdo commented on pkg/sqlite/sql.go
> +	lhs := fmt.Sprintf("(SELECT COUNT(*) FROM %s s WHERE s.%s = %s.id)", joinTable, primaryFK, primaryTable)
I believe you are missing the `IFNULL(..., 0)` around the query, as I had originally. Without that I believe it won't work properly for count = 0 condition.

2021-04-07 11:07 UTC, bnkai commented
- the tag_count is missing from the UI's sort order in the performers page. (manually editing the URL and using it seems to work ok)
- the IS NULL / IS NOT NULL doesnt make sense/work for the _count filters as mentioned in the above post. Is Null returns nothing while Is not Null returns all entries. 
- you can probably ignore this. The  `/scenes?sortby=tag_count&sortdir=desc` was giving me 4 irrelevant scenes as first with fewer tags. I edited->saved those scenes and the sort order is fine now. Not sure why that happened.

2021-04-09 08:17 UTC, bnkai approved these changes

2021-04-09 08:46 UTC, merged