Added rating to performers and studios
stashapp/stash pull request #1308
Opened 2021-04-15 21:36 UTC by julien0221

I added rating on performers and studios page. And I added some tests to it.

2021-04-22 03:50 UTC, WithoutPants requested changes
* setting a rating on a Performer that already is marked as a favourite results in overlapping ribbons in the Performers page:
![image](https://user-images.githubusercontent.com/53250216/115651999-b1865400-a36f-11eb-9637-17557f264806.png)

My suggestion would be to change the favourite ribbon to be a heart icon on the upper right of the performer image.

* rating is not set when creating a performer

2021-04-22 03:50 UTC, WithoutPants commented on ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
> +  const [rating, setRating] = useState<number>(performer?.rating ?? NaN);
Should be using formik values instead.

This use of this means that if you navigate away from the edit page after changing the rating but not saving, then no prompt is displayed about unsaved data.

2021-04-23 20:27 UTC, julien0221 commented
I removed the banner favourite and I added a heart icon on upper right as you suggested.
I changed the setRating to use formik to show the unsaved popup.

I created some performers and I am not sure what you mean with "rating is not set when creating a performer". Because it works all good when I was testing.
Can you give me more details please?

2021-04-26 03:35 UTC, WithoutPants approved these changes
The create bug was fixed with the change to use formik values.

2021-04-26 03:48 UTC, merged

2021-04-26 03:48 UTC, WithoutPants commented
@julien0221 please contact me on Discord to arrange bounty payment.

2021-04-26 15:39 UTC, GsMumbo commented
@julien0221 @WithoutPants It looks like Star Ratings were added to both, but only Performers can be sorted by rating. We’re Studios also supposed to have this sorting too?

(Also thank you! This is amazing!)