[WIP] Filter studio hierarchy
stashapp/stash pull request #1397
Opened 2021-05-17 04:53 UTC by gitgiggety

I've been working on adding support for filtering on studios including their children. This so you can set a filter on a parent studio and for example the scenes for all child studios will be shown as well.

This is a work in progress and I'm currently creating this PR to get feedback. I probably won't be working on this till next weekend so this gives you some time to provide input which I will be able to incorperate then.

The TODOs are:
- [ ] Redesign filter. Currently only a numeric input is shown, might be better to add a checkbox and an optional number input (no number specified is infinite depth, checkbox not checked is depth of 0)
- [ ] Use new filter as well for:
  - [ ] Images
  - [ ] Galleries
- [ ] Add depth setting to Studio tabs(? not sure if needed or works automatically)
  - [ ] Scenes
  - [ ] Images
  - [ ] Galleries
- [ ] Testing

2021-05-22 20:16 UTC, gitgiggety commented
I've rebased the branch on top of #1406 as it would conflict otherwise anyway and it makes it easier to implement as well. Will rebase on develop branch again after #1406 is merged.

2021-05-23 19:05 UTC, gitgiggety commented
I think this is finished / done, but obviously also depends on #1406 being merged.

Applying depth on Studios tabs works kinda automatically because the default filters are applied which can still be edited. So at the top of the list a user can just click the studios filter, check to include children and optionally provide a depth

2021-05-31 08:41 UTC, WithoutPants requested changes
Can you please rebase against develop so the diff doesn't show all of the filter refactor changes?

2021-05-31 12:57 UTC, gitgiggety commented on pkg/sqlite/movies.go
> -	left join studios as studio on studio.id = movies.studio_id
Not sure if I understood you correctly, but I just removed them all and I think it still works

2021-05-31 12:59 UTC, gitgiggety commented
Rebased as I already set I would do after #1406 would be merged. Had some strange Typescript issue in `AddFilter.tsx` with regards to the options thingy, but I believe it's resolved properly without possibly running into issues later on if additional `CriterionValue` types could be added.

2021-06-03 10:50 UTC, WithoutPants approved these changes

2021-06-03 10:52 UTC, merged