Fix: unhandled errors
stashapp/stash pull request #1419
Opened 2021-05-22 18:43 UTC by EnameEtavir

As these errors where not explicitly ignored with _, I made changes to make sure they bubble up.

2021-05-24 22:12 UTC, WithoutPants requested changes

2021-05-24 22:12 UTC, WithoutPants commented on pkg/manager/task_stash_box_tag.go
> +					}
This is redundant - error is returned below.

2021-05-24 22:12 UTC, WithoutPants commented on pkg/api/resolver_query_find_scene.go
> +			}
Redundant - error is returned below.

2021-05-24 22:12 UTC, WithoutPants commented on pkg/api/resolver_query_find_image.go
> +			}
Redundant: returned below.

2021-05-25 08:39 UTC, EnameEtavir commented
I agree, they are redundant, but from a maintainability view they could help you when you refactor the code or add additional steps where you might not see that those errors were not handled in the scope where the originated.

If you still want it removed, I'll do so, just wanted to bring the point up as food for thought.

2021-05-25 08:40 UTC, WithoutPants commented
Decent point. I'll merge as is.

2021-05-25 08:40 UTC, merged