Implement i18n into UI elements
stashapp/stash pull request #1471
Opened 2021-06-02 17:59 UTC by Still34

## Summary

This PR aims to incorporate the existing i18n implementation deeper into the UI elements, bringing i18n to the entire frontend. As a proof-of-concept, the zh-TW localization strings are also included in this PR.

## To-do

Elements with i18n implemented:
- [v] Performer (incl. actions, bio, etc.)
- [v] Tags
- [ ] Button actions
- [ ] Modal dialogs
- [ ] Settings
- [ ] Scenes (incl. editing)
- [ ] Movies (incl. editing)
- [ ] Markers

2021-06-04 22:11 UTC, kermieisinthehouse commented on ui/v2.5/src/locales/en-GB.json
> +      "db_path_head": "Databae Path",
Typo

2021-06-05 07:14 UTC, Still34 commented on ui/v2.5/src/locales/en-GB.json
> +      "db_path_head": "Databae Path",
Resolved.

2021-06-08 04:11 UTC, WithoutPants requested changes
`MovieDetailsPanel` is missing internationalisation.

Apart from the review comments, this appears to test ok.

2021-06-14 04:45 UTC, WithoutPants commented
I've added the following to `en-GB`. This can be added to zh-TW json file in another PR:
```
"plugins": {
      "hooks": "Hooks",
      "triggers_on": "Triggers on"    
}
```

2021-06-14 04:46 UTC, WithoutPants approved these changes

2021-06-14 05:48 UTC, merged