SQLite model refactoring
stashapp/stash pull request #3791
Opened 2023-06-01 00:48 UTC by DingDongSoLong4

This is a bunch of refactoring to move database code from the `models` package into the `sqlite` package, similar to #3057. I have changed only the simplest queries over to using `goqu`, anything remotely complicated has been left as is SQL-wise.

2023-06-04 19:03 UTC, DingDongSoLong4 commented
Alright I think this is ready for review and testing now. I have made changes regarding the zero date validation issue mentioned here in `pkg/sqlite/date.go`, which I will send separately later, since that involves behaviour changes and a database migration.

2023-06-14 02:06 UTC, WithoutPants requested changes
Setting rating during movie create doesn't appear to work correctly.

2023-06-14 20:26 UTC, DingDongSoLong4 commented on internal/api/resolver_mutation_movie.go
> +			scene, err := qb.UpdatePartial(ctx, movieID, updatedMovie)
Oops, fixed now.

2023-06-15 01:43 UTC, WithoutPants approved these changes

2023-06-15 02:46 UTC, merged