Safari video height css fix
stashapp/stash pull request #3882
Opened 2023-07-05 13:08 UTC by NodudeWasTaken

Fixes #3831
Caused by #3729

Moves max-height one layer down and fixes iPad video player not showing up.

Tested on:
- Chrome
- Safari desktop, iOS and in responsive design mode (fake iPad etc.)
- Firefox
- Edge

2023-07-10 17:34 UTC, DingDongSoLong4 commented
Can confirm the video controls are no longer being hidden on iPad :+1:

2023-07-11 01:48 UTC, WithoutPants requested changes
This breaks the layout on desktop for me:

![image](https://github.com/stashapp/stash/assets/53250216/61cfd09e-3f78-40f5-b37a-f8c7d0af1978)

The video player and scrubber now overflow the vertical space, causing the scrollbar to appear.

2023-07-11 18:38 UTC, NodudeWasTaken commented
> This breaks the layout on desktop for me:
> 
> ![image](https://user-images.githubusercontent.com/53250216/252528391-61cfd09e-3f78-40f5-b37a-f8c7d0af1978.png)
> 
> The video player and scrubber now overflow the vertical space, causing the scrollbar to appear.

Should very hopefully be fixed now in all scenarios

2023-07-12 00:45 UTC, WithoutPants approved these changes

2023-07-12 00:45 UTC, merged