Add Icons to tags if they have parent/child tags
stashapp/stash pull request #3931
Opened 2023-07-21 13:05 UTC by elkorol

As guided by DingDongSoLong4, I closed the last pull request to do with this linked [here](https://github.com/stashapp/stash/pull/3916) and started afresh to allow Parent tags and child tags to have a visual indicator on the tags page, if any have any parent or child tags themselves. Giving a visual cue without having to navigate away from current tag. To see if there is any hierarchy in those parent/child tags

2023-08-24 01:42 UTC, WithoutPants requested changes
This causes a regression of https://github.com/stashapp/stash/issues/3656 - the tag popover no longer shows. I think this probably needs to be added to the `TagLink` code instead.

2023-08-24 01:42 UTC, WithoutPants commented on ui/v2.5/src/components/Tags/TagDetails/TagDetailsPanel.tsx
> +          {tag.children.map((p) => (
Why was this changed? Shouldn't this be `parents`?

2023-08-24 01:42 UTC, WithoutPants commented on ui/v2.5/src/components/Tags/TagDetails/TagDetailsPanel.tsx
> +                      >
I don't understand why this overlay is here. Clicking on the icon doesn't do anything different than clicking elsewhere on the badge. The text needs to be internationalised as well.

2023-08-30 05:52 UTC, elkorol commented
Made requested changes. I couldn't get Tooltip to work without using OverlayTrigger. Where am I going wrong with this?

2023-08-30 12:28 UTC, xx790 commented
This PR seems tangential to a feature I would like to have (thought about making a PR but no idea when I might get to it myself - not familiar with the project and with React).

Would love to have ids of the tag and all its parents as data attributes in HTML so I can make custom CSS easier.
Something like this:
```html
<div data-tag-id="1", data-tag-parents="2 3 4" ...>Tag</div>
```

Looking into changes, it seems like tag id might become available at least in some places, am I right?
Do you think it would be a good idea to add parent tags as well?

2023-09-20 03:37 UTC, WithoutPants commented
> This PR seems tangential to a feature I would love to have (thought about making a PR but no idea when I might get to it myself - not familiar with the project and with React).
> 
> Would love to have ids of the tag and all its parents as data attributes in HTML so I can make custom CSS easier. Something like this:
> 
> ```
> <div data-tag-id="1" data-tag-parents="2 3 4" ...>Tag</div>
> ```
> 
> Looking into changes, it seems like tag id might become available at least in some places, am I right? Do you think it would be a good idea to add parent tags as well?

This is possible, but would require changes to the client graphql queries to get the id numbers. It's beyond the scope for this PR.

2023-09-20 04:08 UTC, merged