Video filters and transforms
stashapp/stash pull request #826
Opened 2020-10-02 22:32 UTC by JoeSmithStarkers

WIP in progress for review.

I've added css/svg based video filters to the scene player.

The video filters don't work across all browsers. Chrome is the closest to being fully functional, however an issue occurs when mixing an svg filter with a scale/rotate transformation. Firefox on the other hand is laggy with most filters and a decent sized video.

![videoFilters](https://user-images.githubusercontent.com/60503487/94974771-e3120c00-0552-11eb-882a-cd1c9b1b46ef.png)

2020-10-08 05:05 UTC, WithoutPants commented
While I can't see using this myself, this does cool, and works well based on my cursory tests on Chrome, Firefox and Edge. Haven't yet tried on the iPad. I do think that the Filters tab should probably not be the last tab, since that's the customary location for the Edit tab. The addition of this tab also overflows the tab container when the scene has Movies or a Gallery.

2020-10-10 04:30 UTC, JoeSmithStarkers commented
I've re-ordered the panels, and added an aspect ratio correction slider.

Still have to consider the issue of the overflow.

2020-10-10 07:08 UTC, JoeSmithStarkers commented
Any suggestions on handling the overflow?

2020-10-12 05:45 UTC, WithoutPants commented
```
            <ButtonGroup className="ml-auto">
              <Nav.Item>
                <OCounterButton
                  loading={oLoading}
                  value={scene.o_counter || 0}
                  onIncrement={onIncrementClick}
                  onDecrement={onDecrementClick}
                  onReset={onResetClick}
                />
              </Nav.Item>
              <Nav.Item>{renderOperations()}</Nav.Item>
            </ButtonGroup>
```
This will make it so that the overflow menu and the O-Counter button break together to the next line if needed. That's good enough for me.

2020-10-14 02:54 UTC, WithoutPants requested changes

2020-10-14 02:54 UTC, WithoutPants commented on ui/v2.5/src/components/Scenes/SceneDetails/SceneVideoFilterPanel.tsx
> +      </div>
I don't think this is necessary.

2020-10-22 04:44 UTC, WithoutPants approved these changes

2020-10-22 04:45 UTC, merged